celugadget = "https://shopee.com.co/Celulares-y-Gadgets-cat.11069113?order=asc&page=0&sortBy=price"
ropamujer = "https://shopee.com.co/Ropa-de-Mujer-cat.11069111?order=asc&page=0&sortBy=price"
juguetes = "https://shopee.com.co/Juguetes-y-Hobbies-cat.11069098?order=asc&page=0&sortBy=price"
mascotas = "https://shopee.com.co/Mascotas-cat.11069095?order=asc&page=0&sortBy=price"
electro = "https://shopee.com.co/Electrodom%C3%A9sticos-cat.11069114?order=asc&page=0&sortBy=price"
joyas = "https://shopee.com.co/Joyas-y-Relojes-cat.11069101?order=asc&page=0&sortBy=price"
madrebebe = "https://shopee.com.co/Madre-y-Beb%C3%A9-cat.11069097?order=asc&page=0&sortBy=price"
electronica = "https://shopee.com.co/Electr%C3%B3nica-cat.11069115?order=asc&page=0&sortBy=price"
ropahombre = "https://shopee.com.co/Ropa-de-Hombre-cat.11069104?order=asc&page=0&sortBy=price"
calzadomujer = "https://shopee.com.co/Calzado-de-Mujer-cat.11069110?order=asc&page=0&sortBy=price"
hogarvida = "https://shopee.com.co/Hogar-y-Vida-cat.11069103?order=asc&page=0&sortBy=price"
deportes = "https://shopee.com.co/Deportes-y-Fitness-cat.11069096?order=asc&page=0&sortBy=price"
vehiculos = "https://shopee.com.co/Accesorios-para-Veh%C3%ADculos-cat.11069117?order=asc&page=0&sortBy=price"
bolsasmujer = "https://shopee.com.co/Bolsas-de-Mujer-cat.11069109?order=asc&page=0&sortBy=price"
bolsashombre = "https://shopee.com.co/Bolsas-de-Hombre-cat.11069106?order=asc&page=0&sortBy=price"
belleza = "https://shopee.com.co/Belleza-cat.11069094?order=asc&page=0&sortBy=price"
modabebe = "https://shopee.com.co/Moda-para-Beb%C3%A9s-y-Ni%C3%B1os-cat.11069100?order=asc&page=0&sortBy=price"
salud = "https://shopee.com.co/Salud-cat.11069099?order=asc&page=0&sortBy=price"
calzadomen = "https://shopee.com.co/Calzado-de-Hombre-cat.11069105?order=asc&page=0&sortBy=price"
viajeyequipaje = "https://shopee.com.co/Viajes-y-Equipaje-cat.11069108?order=asc&page=0&sortBy=price"
accesoriosmoda = "https://shopee.com.co/Accesorios-de-Moda-cat.11069102?order=asc&page=0&sortBy=price"
computacion = "https://shopee.com.co/Computaci%C3%B3n-cat.11069107?order=asc&page=0&sortBy=price"
papeleria = "https://shopee.com.co/Papeler%C3%ADa-cat.11069116?order=asc&page=0&sortBy=price"

# creando una lista con las variables anteriores
links = [celugadget, ropamujer, juguetes, mascotas, electro, joyas, madrebebe, electronica, ropahombre, calzadomujer, hogarvida, deportes, vehiculos, bolsasmujer, bolsashombre, belleza, modabebe, salud, calzadomen, viajeyequipaje, accesoriosmoda, computacion, papeleria]
